# Generated by Django 2.2.5 on 2019-10-20 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('img_url', models.ImageField(null=True, storage=main.storage.ImageStorage(), upload_to='img')),
                ('cmpScore', models.IntegerField(null=True)),
                ('like', models.IntegerField(null=True)),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commend',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Img')),
            ],
        ),
    ]
