# Generated by Django 2.2.6 on 2019-10-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_img_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='cmpScore',
            field=models.FloatField(null=True),
        ),
    ]
