# Generated by Django 2.2.6 on 2019-10-28 12:07

from django.db import migrations
import main.listField


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191024_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='label',
            field=main.listField.ListField(null=True, token=','),
        ),
    ]
